const TYPE =  {
  
  SOCCKET : {
    SETTER: "SOCCKET_SETTER"
  },
  AUTH: {
    SETTER: "AUTH_SETTER"
  },
  CONVERTATION: {
    SETTER: "CONVERTATION_SETTER",
    CHANGE: "CONVERTATION_CHANGE"
  },
  MESSAGE: {
    SETTER: "MESSAGE_SETTER"
  },
  CONFIG: {
    SETTER_CONFIG : "SETTER_CONFIG"
  }
}
export default TYPE;