const TYPE =  {
  HOME : {
    CHANGE_LAYOUTS: 'CHANGE_LAYOUTS',
    CHANGE_THEME  : 'CHANGE_THEME'
  },
  CHAT : {
    CHANGE_USER_CHAT_DEFAULT: 'CHANGE_USER_CHAT_DEFAULT'
  },
  SOCCKET : {
    SET_SOCKET_IO: "SET_SOCKET_IO"
  },
  USER: {
    SETTER_USER: "SETTER_USER"
  },
  CHANNEL: {
    SETTER_CHANNEL        : "SETTER_CHANNEL",
    ADD_MESSAGE           : "ADD_MESSAGE",
    ADD_MESSAGE_SEND_TO_ME: "ADD_MESSAGE_SEND_TO_ME",
    SET_ACTIVE            : "SET_ACTIVE",
    ADD_USER_ONLINE       : "ADD_USER_ONLINE",
    REMOVE_USER_ONLINE    : "REMOVE_USER_ONLINE",
    READ_ALL_MESSAGE_CHANNEL_ACTIVE: "READ_ALL_MESSAGE_CHANNEL_ACTIVE"
  },
  CONFIG: {
    SETTER_SEND_PEER : "SETTER_SEND_PEER"
  }
}
export default TYPE;